app/views/home.py
from flask import Blueprint, render_template, request, redirect, session, url_for, flash
import hashlib
from app.service.user_service import is_user, add_first_user


home=Blueprint('home',__name__, template_folder='templates')

@home.route('/')
def homepage():
   return render_template("homepage/homepage.html")

@home.route('/about')
def about():
    return render_template("homepage/about.html")

@home.route('/sign_in', methods=['GET', 'POST'])
def sign_in():
   if request.method == 'POST':
       user=is_user(request.form)
       if user:
           session['user']=user
           return redirect("/auth/account")
       else:
           return render_template("homepage/sign_in.html", error="Bad credentials!")
   return render_template("homepage/sign_in.html")


@home.route('/sign_up', methods=['GET', 'POST'])
def sign_up():
    if request.method == 'POST':
        print(f"request.form = {request.form}")
        user=is_user(request.form)
        if not user:
            print("OK")
            add_first_user(request.form)
            return redirect("/sign_in")
        else:
            return render_template("homepage/sign_up.html", error="User with this parameters already exist!") 
    return render_template("homepage/sign_up.html")   
    

app/templates/homepage/about.html
{% extends 'layout.html' %}
{% block content %}

<section class="how-to-start home">
    <img src="static/img/logo1.webp" alt="aaa" class="how-to-image">
    <h3>How to start?</h3>
    <p>If you are new here - start with registration, then you can add other family members and define their properties
    <br>If you are already registered in the system as a family member (your family member has registered you), log in with your username and password</p>
</section>

{% endblock %}

app/templates/homepage/homepage.html
{% extends 'layout.html' %}
{% block content %}

<section class="Intro home">
    <h>Family Finance Management</h>
    <img src="static/img/img.jpg" alt="Family Finance Image" class="header-image">
    <h1>Welcome!</h1>
    <p>Managing family finances can be challenging, but it doesnt have to be. Our app helps families track expenses,
        set budgets, and reach financial goals—together. Whether its teaching kids about money, keeping an eye on
        shared family expenses, or planning for the future, Our appliacation offers easy-to-use tools for every member
        of the family.
        With dedicated profiles for parents, kids, and admins, everyone can stay informed and involved. Our goal is to
        make family financial management a seamless, collaborative, and rewarding experience. Lets take control of your
        familys financial future today!</p>
</section>
<footer>
    <span>2024 - Family Budget</span>
</footer>
{% endblock %}


app/templates/homepage/sign_in.html
{% extends 'layout.html' %}
{% block content %}
<section class="form-section">
    <div class="form-container">
        <h2>Sign In</h2>
        {% if error %}
        <div class="error-message">{{ error }}</div>
        {% endif %}
        
        <form class="sign" action="{{ url_for('home.sign_in') }}" method="POST">
            <label for="username">User Name:</label>
            <input type="text" id="username" name="username" placeholder="Enter your username" required>
            <label for="password">Password:</label>
            <input type="password" id="password" name="password" placeholder="Enter your password" required>

            <button type="submit" class="btn-signin">SIGN IN</button>
        </form>
        <div class="signup-link">
            <p>Want register family?</p>
            <a class="btn-signup", href="{{ url_for('home.sign_up') }}"> SIGN UP</a>
        </div>
    </div>
</section>
{% endblock %}

app/templates/homepage/sign_up.html
{% extends 'layout.html' %}
{% block content %}
<section class="form-section">
    <div class="form-container">
        <h2>Sign up</h2>
        {% if error %}
        <div class="error-message">{{ error }}</div>
        {% endif %}
        <form class="signup" action="/sign_up" method="POST">
            <label for="fullname">Full name:</label>
            <input type="text" id="fullname" name="fullname" placeholder="Enter your fullname" required>

            <label for="username">User name:</label>
            <input type="text" id="username" name="username" placeholder="Enter your username" required>

            <label for="email">Email:</label>
            <input type="text" id="email" name="email" placeholder="Enter your email">

            <label for="password">Password:</label>
            <input type="password" id="password" name="password" placeholder="Enter your password" required>

            <button type="submit" class="btn-signin">SIGN UP</button>
        </form>
    </div>
</section>
{% endblock %}